name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Swift tests
      env: TEST_SECRET=${{ secrets.DARKSKY_SECRET }}
      run: |
        echo "Starting swift builds"
        swift test
